global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

rule_files:
  - "/etc/prometheus/rules/alerts.yml"

scrape_configs:
  # 1. Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Node Exporter (Infrastructure)
  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - '10.0.1.7:9100'   # Broker 1
        - '10.0.1.244:9100' # Broker 2
        - '10.0.2.185:9100' # Broker 3
        - '10.0.2.91:9100'  # Broker 4
        - '10.0.1.240:9100' # Controller 1
        - '10.0.2.70:9100'  # Controller 2
        - '10.0.3.250:9100' # Controller 3
        - '10.0.1.80:9100'  # Kafka Connect

  # 3. KAFKA CLUSTER
  - job_name: 'kafka'
    static_configs:
      # --- Brokers (Port 8080) ---
      - targets:
        - '10.0.1.7:8080'
        - '10.0.1.244:8080'
        - '10.0.2.185:8080'
        - '10.0.2.91:8080'
        labels:
          role: 'broker'
          env: 'production'

      # --- Controllers (Port 8079) ---
      - targets:
        - '10.0.1.240:8079'
        - '10.0.2.70:8079'
        - '10.0.3.250:8079'
        labels:
          role: 'controller'
          env: 'production'

  # 4. Kafka Connect
  - job_name: 'kafka-connect'
    static_configs:
      - targets:
        - '10.0.1.80:8079'
        labels:
          role: 'connect'
          env: 'production'
