all:
  vars: 
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/ubuntu/kafka-key.pem
    ansible_become: true
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    custom_log4j2: false

    ssl_enabled: true
    ssl_self_signed: true
    regenerate_ca: true
    regenerate_keystore_and_truststore: true

    sasl_protocol: scram
    sasl_mechanism: SCRAM-SHA-512
    
    kafka_controller_sasl_protocol: plain,scram
    kafka_controller_sasl_mechanism: PLAIN

    sasl_scram_users:
      admin:
        principal: admin
        password: admin-secret-password
      client:
        principal: client
        password: client-secret-password

    sasl_plain_users:
      admin:
        principal: admin
        password: admin-secret-password

    kafka_broker_sasl_user: admin
    kafka_controller_sasl_user: admin
    kafka_connect_sasl_user: admin


    kafka_broker_custom_listeners:
      internal:
        name: INTERNAL
        port: 9092
        ssl_enabled: true
        sasl_protocol: scram


    kafka_broker_inter_broker_listener_name: internal


    kafka_controller_custom_listeners:
      controller:
        name: CONTROLLER
        port: 9093
        ssl_enabled: true
        sasl_protocol: plain

    kafka_controller_inter_controller_listener_name: controller

    kafka_controller_quorum_voters: "3001@ip-10-0-1-240.eu-central-1.compute.internal:9093,3002@ip-10-0-2-70.eu-central-1.compute.internal:9093,3003@ip-10-0-3-250.eu-central-1.compute.internal:9093"

kafka_controller:
  hosts:
    ip-10-0-1-240.eu-central-1.compute.internal:
      ansible_host: 10.0.1.240
      kafka_controller_id: 3001
      node_id: 3001
    ip-10-0-2-70.eu-central-1.compute.internal:
      ansible_host: 10.0.2.70
      kafka_controller_id: 3002
      node_id: 3002
    ip-10-0-3-250.eu-central-1.compute.internal:
      ansible_host: 10.0.3.250
      kafka_controller_id: 3003
      node_id: 3003

kafka_broker:
  hosts:
    ip-10-0-1-7.eu-central-1.compute.internal:
      ansible_host: 10.0.1.7
      node_id: 1
    ip-10-0-1-244.eu-central-1.compute.internal:
      ansible_host: 10.0.1.244
      node_id: 2
    ip-10-0-2-185.eu-central-1.compute.internal:
      ansible_host: 10.0.2.185
      node_id: 3
    ip-10-0-2-91.eu-central-1.compute.internal:
      ansible_host: 10.0.2.91
      node_id: 4

kafka_connect:
  hosts:
    ip-10-0-1-80.eu-central-1.compute.internal:
      ansible_host: 10.0.1.80

zookeeper:
  hosts: {}