all:
  vars:
    # --- Bağlantı Ayarları ---
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/ubuntu/kafka-key.pem
    ansible_become: true

    ssl_enabled: true
    ssl_self_signed: true

    sasl_protocol: scram
    sasl_mechanism: SCRAM-SHA-512

    sasl_users:
      admin:
        principal: admin
        password: admin-secret-password
      client:
        principal: client
        password: client-secret-password

    kafka_broker_sasl_user: admin
    kafka_controller_sasl_user: admin
    kafka_connect_sasl_user: admin

    kafka_broker_listeners:
      sasl_ssl:
        name: SASL_SSL
        port: 9092

    kafka_broker_inter_broker_listener_name: sasl_ssl
    kafka_broker_inter_broker_protocol_version: "4.1"


kafka_controller:
  vars:
    kafka_controller_sasl_protocol: plain
    kafka_controller_sasl_mechanism: PLAIN

    kafka_controller_listeners:
      controller:
        name: CONTROLLER
        port: 9093

    kafka_controller_inter_controller_listener_name: controller
    kafka_controller_inter_controller_protocol_version: "4.1"

    kafka_controller_quorum_voters: "1@10.0.1.210:9093,2@10.0.2.174:9093,3@10.0.3.97:9093"

  hosts:
    10.0.1.210:
      kafka_controller_id: 1
      node_id: 1
    10.0.2.174:
      kafka_controller_id: 2
      node_id: 2
    10.0.3.97:
      kafka_controller_id: 3
      node_id: 3

kafka_broker:
  hosts:
    10.0.1.42:
      kafka_broker_id: 1
    10.0.1.224:
      kafka_broker_id: 2
    10.0.2.165:
      kafka_broker_id: 3
    10.0.2.80:
      kafka_broker_id: 4

kafka_connect:
  hosts:
    10.0.1.19:

zookeeper:
  hosts: {}